dist: trusty
language: node_js
node_js:
  - node
install:
  - sh install-aseprite.sh
  - npm install
script:
  - npm run-script ci
cache:
  directories:
    - ephemeral/aseprite-bin/
    - node_modules
    - ephemeral/environments/production
